services:
  mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ARCADE_SERVER_TRANSPORT=http
      - ARCADE_SERVER_HOST=0.0.0.0
      - ARCADE_SERVER_PORT=8001
