{
  "openapi": "3.0.1",
  "info": {
    "title": "Marketing Campaigns Public Api",
    "description": "Basepom for all HubSpot Projects",
    "version": "v3",
    "x-hubspot-product-tier-requirements": {
      "marketing": "PROFESSIONAL",
      "sales": "FREE",
      "service": "FREE",
      "cms": "FREE",
      "commerce": "FREE",
      "crmHub": "FREE",
      "dataHub": "FREE"
    },
    "x-hubspot-related-documentation": [
      {
        "name": "Campaigns",
        "url": "https://developers.hubspot.com/docs/guides/api/marketing/campaigns"
      }
    ],
    "x-hubspot-introduction": "You can use campaign endpoints to create, read, update, and delete marketing campaign data. For example, you can use these endpoints to create and manage HubSpot campaigns from your external applications. You can also transfer campaign data to external data warehouses for analytics.",
    "x-moar-merged": true,
    "x-moar-merged-count": 6
  },
  "servers": [
    {
      "url": "https://api.hubapi.com"
    }
  ],
  "tags": [
    {
      "name": "Campaign Budget"
    },
    {
      "name": "Basic"
    },
    {
      "name": "Batch"
    },
    {
      "name": "Campaign"
    },
    {
      "name": "Campaign Asset"
    },
    {
      "name": "Campaign Reporting"
    },
    {
      "name": "Campaign Spend"
    },
    {
      "name": "Forms"
    },
    {
      "name": "Public_VNext_Emails"
    },
    {
      "name": "Marketing Emails"
    },
    {
      "name": "Statistics"
    },
    {
      "name": "Add event attendees"
    },
    {
      "name": "List Associations"
    },
    {
      "name": "Settings"
    },
    {
      "name": "Retrieve Participant State"
    },
    {
      "name": "Change property"
    },
    {
      "name": "Identifiers"
    },
    {
      "name": "Subscriber State Changes"
    },
    {
      "name": "Single_Send"
    },
    {
      "name": "Public SMTP tokens"
    },
    {
      "name": "Single send"
    }
  ],
  "paths": {
    "/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}": {
      "get": {
        "tags": [
          "Campaign Spend"
        ],
        "summary": "Read campaign spend item",
        "description": "Read a campaign spend item by its spendId",
        "operationId": "get-/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}",
        "security": [
          {
            "oauth2": [
              "marketing.campaigns.read"
            ]
          },
          {
            "private_apps": [
              "marketing.campaigns.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "put": {
        "tags": [
          "Campaign Spend"
        ],
        "summary": "Update campaign spend item",
        "description": "Update a specific campaign spend item by ID",
        "operationId": "put-/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 4,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Campaign Spend"
        ],
        "summary": "Delete campaign spend item",
        "description": "Delete a specific campaign spend item by ID",
        "operationId": "delete-/marketing/v3/campaigns/{campaignGuid}/spend/{spendId}",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/batch/update": {
      "post": {
        "tags": [
          "Batch"
        ],
        "summary": "Update a batch of campaigns",
        "description": "This endpoint updates a batch of campaigns based on the provided input data.\nThe maximum number of items in a batch request is 50.\nIf an empty string (\"\") is passed for any property in the Batch Update, it will reset that property's value.",
        "operationId": "post-/marketing/v3/campaigns/batch/update",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 1,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}": {
      "get": {
        "tags": [
          "Campaign Budget"
        ],
        "summary": "Get budget item",
        "description": "Get a specific budget item by ID",
        "operationId": "get-/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}",
        "security": [
          {
            "oauth2": [
              "marketing.campaigns.read"
            ]
          },
          {
            "private_apps": [
              "marketing.campaigns.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "put": {
        "tags": [
          "Campaign Budget"
        ],
        "summary": "Update budget item",
        "description": "Update a specific budget item by ID",
        "operationId": "put-/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 4,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Campaign Budget"
        ],
        "summary": "Delete budget item",
        "description": "Delete a specific budget item by ID",
        "operationId": "delete-/marketing/v3/campaigns/{campaignGuid}/budget/{budgetId}",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}": {
      "put": {
        "tags": [
          "Campaign Asset"
        ],
        "summary": "Add asset association",
        "description": "Associate a specified asset with a campaign. Using the API, you can create and remove associations for the following asset types: forms, static lists, external website pages, sequences, meetings, playbooks, feedback surveys, podcast episodes, sales documents, marketing emails, case studies, knowledge base articles, calls, and CTAs. \n\nFor other asset types, it is recommended to manage your associations directly in the campaign tool in HubSpot.",
        "operationId": "put-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Campaign Asset"
        ],
        "summary": "Remove asset association",
        "description": "Disassociate a specified asset from a campaign.\nImportant: Currently, only the following asset types can be associated and disassociated via the API: Forms, Static lists, External website pages",
        "operationId": "delete-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/budget/totals": {
      "get": {
        "tags": [
          "Campaign Budget"
        ],
        "summary": "Read budget",
        "description": "Retrieve detailed information about the budget and spend items for a specified campaign, including the total budget, total spend, and remaining budget.\nBudget and Spend items may be returned in any order, but the order field specifies their sequence based on the creation date. The item with order 0 is the oldest, and items with higher order values are newer",
        "operationId": "get-/marketing/v3/campaigns/{campaignGuid}/budget/totals",
        "security": [
          {
            "oauth2": [
              "marketing.campaigns.read"
            ]
          },
          {
            "private_apps": [
              "marketing.campaigns.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/batch/read": {
      "post": {
        "tags": [
          "Batch"
        ],
        "summary": "Read a batch of campaigns",
        "description": "This endpoint reads a batch of campaigns based on the provided input data and returns the campaigns along with their associated assets. \nThe maximum number of items in a batch request is 50.\nThe campaigns in the response are not guaranteed to be in the same order as they were provided in the request.\nIf duplicate campaign IDs are provided in the request, duplicates will be ignored. The response will include only unique IDs and will be returned without duplicates.\n",
        "operationId": "post-/marketing/v3/campaigns/batch/read",
        "security": [
          {
            "oauth2": [
              "marketing.campaigns.read"
            ]
          },
          {
            "private_apps": [
              "marketing.campaigns.read"
            ]
          }
        ],
        "x-moar-primitive-count": 1,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Campaign search",
        "description": "This endpoint allows users to search for and return a page of campaigns based on various query parameters. Users can filter by name, sort, and paginate through the campaigns, as well as control which properties are returned in the response.",
        "operationId": "get-/marketing/v3/campaigns/",
        "security": [
          {
            "oauth2": [
              "marketing.campaigns.read"
            ]
          },
          {
            "private_apps": [
              "marketing.campaigns.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Create a campaign",
        "description": "Create a campaign with the given properties and return the campaign object, including the campaignGuid and created properties. ",
        "operationId": "post-/marketing/v3/campaigns/",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/reports/metrics": {
      "get": {
        "tags": [
          "Campaign Reporting"
        ],
        "summary": "Get Campaign Metrics\n",
        "description": "This endpoint retrieves key attribution metrics for a specified campaign, such as sessions, new contacts, and influenced contacts.",
        "operationId": "get-/marketing/v3/campaigns/{campaignGuid}/reports/metrics",
        "security": [
          {
            "oauth2": [
              "marketing.campaigns.read"
            ]
          },
          {
            "private_apps": [
              "marketing.campaigns.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}": {
      "get": {
        "tags": [
          "Campaign Asset"
        ],
        "summary": "List assets",
        "description": "This endpoint lists all assets of the campaign by asset type. The assetType parameter is required, and each request can only fetch assets of a single type.\nAsset metrics can also be fetched along with the assets; they are available only if start and end dates are provided.",
        "operationId": "get-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}",
        "security": [
          {
            "oauth2": [
              "marketing.campaigns.read"
            ]
          },
          {
            "private_apps": [
              "marketing.campaigns.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/batch/archive": {
      "post": {
        "tags": [
          "Batch"
        ],
        "summary": "Delete a batch of campaigns",
        "description": "This endpoint deletes a batch of campaigns. \nThe maximum number of items in a batch request is 50.\nThe response will always be 204 No Content, regardless of whether the campaigns exist or not, whether they were successfully deleted or not, or if only some of the campaigns in the batch were deleted.",
        "operationId": "post-/marketing/v3/campaigns/batch/archive",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 1,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/reports/revenue": {
      "get": {
        "tags": [
          "Campaign Reporting"
        ],
        "summary": "Fetch revenue",
        "description": "Fetch revenue attribution report data for a specified campaign\n",
        "operationId": "get-/marketing/v3/campaigns/{campaignGuid}/reports/revenue",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.revenue.read"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.revenue.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/batch/create": {
      "post": {
        "tags": [
          "Batch"
        ],
        "summary": "Create a batch of campaigns",
        "description": "This endpoint creates a batch of campaigns. The maximum number of items in a batch request is 50.\nThe campaigns in the response are not guaranteed to be in the same order as they were provided in the request.",
        "operationId": "post-/marketing/v3/campaigns/batch/create",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/budget": {
      "post": {
        "tags": [
          "Campaign Budget"
        ],
        "summary": "Add budget item",
        "description": "Add a new budget item to the campaign",
        "operationId": "post-/marketing/v3/campaigns/{campaignGuid}/budget",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 4,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Read a campaign",
        "description": "Get a campaign identified by a specific campaignGuid with the given properties. Along with the campaign information, it also returns information about assets. Depending on the query parameters used, this can also be used to return information about the corresponding assets' metrics. Metrics are available only if startDate and endDate are provided.",
        "operationId": "get-/marketing/v3/campaigns/{campaignGuid}",
        "security": [
          {
            "oauth2": [
              "marketing.campaigns.read"
            ]
          },
          {
            "private_apps": [
              "marketing.campaigns.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Campaign"
        ],
        "summary": "Delete campaign ",
        "description": "Delete a specified campaign from the system.\nThis call will return a 204 No Content response regardless of whether the campaignGuid provided corresponds to an existing campaign or not.",
        "operationId": "delete-/marketing/v3/campaigns/{campaignGuid}",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "Basic"
        ],
        "summary": "Update campaign",
        "description": "Perform a partial update of a campaign identified by the specified campaignGuid. Provided property values will be overwritten. Read-only and non-existent properties will cause 400 error.\nIf an empty string is passed for any property in the Batch Update, it will reset that property's value.\n",
        "operationId": "patch-/marketing/v3/campaigns/{campaignGuid}",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/reports/contacts/{contactType}": {
      "get": {
        "tags": [
          "Campaign Reporting"
        ],
        "summary": "Fetch contact IDs",
        "description": "Fetch the list of contact IDs for the specified campaign and contact type",
        "operationId": "get-/marketing/v3/campaigns/{campaignGuid}/reports/contacts/{contactType}",
        "security": [
          {
            "oauth2": [
              "marketing.campaigns.read"
            ]
          },
          {
            "private_apps": [
              "marketing.campaigns.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/campaigns/{campaignGuid}/spend": {
      "post": {
        "tags": [
          "Campaign Spend"
        ],
        "summary": "Create campaign spend item",
        "description": "Create a new campaign spend item",
        "operationId": "post-/marketing/v3/campaigns/{campaignGuid}/spend",
        "security": [
          {
            "private_apps": [
              "marketing.campaigns.write"
            ]
          },
          {
            "oauth2": [
              "marketing.campaigns.write"
            ]
          }
        ],
        "x-moar-primitive-count": 4,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/forms/{formId}": {
      "get": {
        "tags": [
          "Forms"
        ],
        "summary": "Get a form definition",
        "description": "Returns a form based on the form ID provided.",
        "operationId": "get-/marketing/v3/forms/{formId}_getById",
        "security": [
          {
            "oauth2": [
              "forms"
            ]
          },
          {
            "private_apps": [
              "forms"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "put": {
        "tags": [
          "Forms"
        ],
        "summary": "Update a form definition",
        "description": "Update all fields of a hubspot form definition.",
        "operationId": "put-/marketing/v3/forms/{formId}_replace",
        "security": [
          {
            "oauth2": [
              "forms"
            ]
          },
          {
            "private_apps": [
              "forms"
            ]
          }
        ],
        "x-moar-primitive-count": 215,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Forms"
        ],
        "summary": "Archive a form definition",
        "description": "Archive a form definition. New submissions will not be accepted and the form definition will be permanently deleted after 3 months.",
        "operationId": "delete-/marketing/v3/forms/{formId}_archive",
        "security": [
          {
            "oauth2": [
              "forms"
            ]
          },
          {
            "private_apps": [
              "forms"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "Forms"
        ],
        "summary": "Partially update a form definition",
        "description": "Update some of the form definition components",
        "operationId": "patch-/marketing/v3/forms/{formId}_update",
        "security": [
          {
            "oauth2": [
              "forms"
            ]
          },
          {
            "private_apps": [
              "forms"
            ]
          }
        ],
        "x-moar-primitive-count": 209,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/forms/": {
      "get": {
        "tags": [
          "Forms"
        ],
        "summary": "Get a list of forms",
        "description": "Returns a list of forms based on the search filters. By default, it returns the first 20 `hubspot` forms",
        "operationId": "get-/marketing/v3/forms/_getPage",
        "security": [
          {
            "oauth2": [
              "forms"
            ]
          },
          {
            "private_apps": [
              "forms"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "post": {
        "tags": [
          "Forms"
        ],
        "summary": "Create a form",
        "description": "Add a new `hubspot` form",
        "operationId": "post-/marketing/v3/forms/_create",
        "security": [
          {
            "oauth2": [
              "forms"
            ]
          },
          {
            "private_apps": [
              "forms"
            ]
          }
        ],
        "x-moar-primitive-count": 1,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/statistics/list": {
      "get": {
        "tags": [
          "Statistics"
        ],
        "summary": "Get aggregated statistics",
        "description": "Use this endpoint to get aggregated statistics of emails sent in a specified time span. It also returns the list of emails that were sent during the time span.",
        "operationId": "get-/marketing/v3/emails/statistics/list",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}/publish": {
      "post": {
        "tags": [
          "Public_VNext_Emails"
        ],
        "operationId": "post-/marketing/v3/emails/{emailId}/publish",
        "security": [
          {
            "oauth2": [
              "marketing-email"
            ]
          },
          {
            "private_apps": [
              "marketing-email"
            ]
          },
          {
            "oauth2": [
              "transactional-email"
            ]
          },
          {
            "private_apps": [
              "transactional-email"
            ]
          }
        ],
        "x-hubspot-rate-limit-exemptions": [
          "ten-secondly"
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/ab-test/create-variation": {
      "post": {
        "tags": [
          "Public_VNext_Emails"
        ],
        "summary": "Create an A/B test variation",
        "description": "Create a new variation for an email A/B test",
        "operationId": "post-/marketing/v3/emails/ab-test/create-variation",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/statistics/histogram": {
      "get": {
        "tags": [
          "Statistics"
        ],
        "summary": "Get aggregated statistic intervals",
        "description": "Get aggregated statistics in intervals for a specified time span. Each interval contains aggregated statistics of the emails that were sent in that time.",
        "operationId": "get-/marketing/v3/emails/statistics/histogram",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}/ab-test/get-variation": {
      "get": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Get the variation of a an A/B marketing email",
        "description": "This endpoint lets you obtain the variation of an A/B marketing email. If the email is variation A (master) it will return variation B (variant) and vice versa.",
        "operationId": "get-/marketing/v3/emails/{emailId}/ab-test/get-variation",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}/draft/reset": {
      "post": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Reset Draft",
        "description": "Resets the draft back to a copy of the live object.",
        "operationId": "post-/marketing/v3/emails/{emailId}/draft/reset",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}/revisions/{revisionId}/restore-to-draft": {
      "post": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Restore a revision of a marketing email to DRAFT state",
        "description": "Restores a previous revision of a marketing email to DRAFT state. If there is currently something in the draft for that object, it is overwritten. ",
        "operationId": "post-/marketing/v3/emails/{emailId}/revisions/{revisionId}/restore-to-draft",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}/draft": {
      "get": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Get draft version of a marketing email",
        "description": "Get the draft version of an email (if it exists). If no draft version exists, the published email is returned.",
        "operationId": "get-/marketing/v3/emails/{emailId}/draft",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Create or update draft version",
        "description": "Create or update the draft version of a marketing email. If no draft exists, the system creates a draft from the current \u201clive\u201d email then applies the request body to that draft. The draft version only lives on the buffer\u2014the email is not cloned.",
        "operationId": "patch-/marketing/v3/emails/{emailId}/draft",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 108,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}/revisions": {
      "get": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Get revisions of a marketing email",
        "description": "Get a list of all versions of a marketing email, with each entry including the full state of that particular version. The current revision has the ID -1.",
        "operationId": "get-/marketing/v3/emails/{emailId}/revisions",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}/unpublish": {
      "post": {
        "tags": [
          "Public_VNext_Emails"
        ],
        "operationId": "post-/marketing/v3/emails/{emailId}/unpublish",
        "security": [
          {
            "oauth2": [
              "marketing-email"
            ]
          },
          {
            "private_apps": [
              "marketing-email"
            ]
          },
          {
            "oauth2": [
              "transactional-email"
            ]
          },
          {
            "private_apps": [
              "transactional-email"
            ]
          }
        ],
        "x-hubspot-rate-limit-exemptions": [
          "ten-secondly"
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}/revisions/{revisionId}": {
      "get": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Get a revision of a marketing email.",
        "description": "Get a specific revision of a marketing email.",
        "operationId": "get-/marketing/v3/emails/{emailId}/revisions/{revisionId}",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/clone": {
      "post": {
        "tags": [
          "Public_VNext_Emails"
        ],
        "summary": "Clone an email",
        "description": "Clone an existing email",
        "operationId": "post-/marketing/v3/emails/clone",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 3,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/": {
      "get": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Get all marketing emails for a HubSpot account.",
        "description": "The results can be filtered, allowing you to find a specific set of emails. See the table below for a full list of filtering options.",
        "operationId": "get-/marketing/v3/emails/",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "post": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Create a new marketing email.",
        "description": "Use this endpoint to create a new marketing email.",
        "operationId": "post-/marketing/v3/emails/",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 109,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}/revisions/{revisionId}/restore": {
      "post": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Restore a revision of a marketing email",
        "description": "Restores a previous revision of a marketing email. The current revision becomes old, and the restored revision is given a new version number.",
        "operationId": "post-/marketing/v3/emails/{emailId}/revisions/{revisionId}/restore",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/emails/{emailId}": {
      "get": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Get the details of a specified marketing email.",
        "description": "Get the details for a marketing email.",
        "operationId": "get-/marketing/v3/emails/{emailId}",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Delete an email",
        "description": "Delete an existing marketing email.",
        "operationId": "delete-/marketing/v3/emails/{emailId}",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "Marketing Emails"
        ],
        "summary": "Update a marketing email.",
        "description": "Change properties of a marketing email.",
        "operationId": "patch-/marketing/v3/emails/{emailId}",
        "security": [
          {
            "oauth2": [
              "content"
            ]
          },
          {
            "private_apps": [
              "content"
            ]
          }
        ],
        "x-moar-primitive-count": 108,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown": {
      "get": {
        "tags": [
          "Retrieve Participant State"
        ],
        "summary": "Read participations breakdown by Marketing Event internal identifier",
        "description": "Read Marketing event's participations breakdown with optional filters by internal identifier marketingEventId.",
        "operationId": "get-/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown_getParticipationsBreakdownByMarketingEventId",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create": {
      "post": {
        "tags": [
          "Add event attendees"
        ],
        "summary": "Record Participants by ContactId with Marketing Event External Ids",
        "description": "Records the participation of multiple HubSpot contacts in a Marketing Event using their HubSpot contact IDs.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
        "operationId": "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_recordByContactIds",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert": {
      "post": {
        "tags": [
          "Subscriber State Changes"
        ],
        "summary": "Record a subscriber state by contact ID",
        "description": "Record a subscriber state between multiple HubSpot contacts and a marketing event, using HubSpot contact IDs. Note that the contact must already exist in HubSpot; a contact will not be created.",
        "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_upsertByContactId",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}": {
      "get": {
        "tags": [
          "Basic"
        ],
        "summary": "Get Marketing Event by External IDs",
        "description": "Returns the details of a Marketing Event with the specified externalAccountId, externalEventId, if it exists.\n\nOnly Marketing Events created by the same app making the request can be retrieved.",
        "operationId": "get-/marketing/v3/marketing-events/events/{externalEventId}_getDetails",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "put": {
        "tags": [
          "Basic"
        ],
        "summary": "Create or update a marketing event",
        "description": "Upserts a marketing event If there is an existing marketing event with the specified ID, it will be updated; otherwise a new event will be created.",
        "operationId": "put-/marketing/v3/marketing-events/events/{externalEventId}_upsert",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 30,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Basic"
        ],
        "summary": "Delete Marketing Event by External Ids",
        "description": "Deletes the existing Marketing Event with the specified externalAccountId, externalEventId, if it exists.\n\nOnly Marketing Events created by the same app can be deleted.",
        "operationId": "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "Basic"
        ],
        "summary": "Update Marketing Event by External IDs",
        "description": "Updates the details of an existing Marketing Event identified by its externalAccountId, externalEventId if it exists.\n\nOnly Marketing Events created by the same app can be updated.",
        "operationId": "patch-/marketing/v3/marketing-events/events/{externalEventId}_update",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 28,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/events/upsert": {
      "post": {
        "tags": [
          "Batch"
        ],
        "summary": "Create or Update Multiple Marketing Events",
        "description": "Upserts multiple Marketing Events. If a Marketing Event with the specified ID already exists, it will be updated; otherwise, a new event will be created.\n\nOnly Marketing Events originally created by the same app can be updated.",
        "operationId": "post-/marketing/v3/marketing-events/events/upsert_upsert",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 30,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create": {
      "post": {
        "tags": [
          "Add event attendees"
        ],
        "summary": "Record Participants by Email with Marketing Event External Ids",
        "description": "Records the participation of multiple HubSpot contacts in a Marketing Event using their email addresses.\n\nIf a contact does not exist, it will be automatically created. The contactProperties field is used exclusively for creating new contacts and will not update properties of existing contacts.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
        "operationId": "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_recordByContactEmails",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown": {
      "get": {
        "tags": [
          "Retrieve Participant State"
        ],
        "summary": "Read participations breakdown by Marketing Event external identifier",
        "description": "Read Marketing event's participations breakdown with optional filters by externalAccountId and externalEventId pair.",
        "operationId": "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown_getParticipationsBreakdownByExternalEventId",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/{objectId}": {
      "get": {
        "tags": [
          "Basic"
        ],
        "summary": "Get Marketing Event by objectId",
        "description": "Returns the details of a Marketing Event with the specified objectId, if it exists.",
        "operationId": "get-/marketing/v3/marketing-events/{objectId}_getByObjectId",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Basic"
        ],
        "summary": "Delete Marketing Event by objectId",
        "description": "Deletes the existing Marketing Event with the specified objectId, if it exists.",
        "operationId": "delete-/marketing/v3/marketing-events/{objectId}_archiveByObjectId",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "Basic"
        ],
        "summary": "Update Marketing Event by objectId",
        "description": "Updates the details of an existing Marketing Event identified by its objectId, if it exists.",
        "operationId": "patch-/marketing/v3/marketing-events/{objectId}_updateByObjectId",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 27,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists": {
      "get": {
        "tags": [
          "List Associations"
        ],
        "summary": "Get lists associated with a marketing event",
        "description": "Gets lists associated with a marketing event by external account id and external event id",
        "operationId": "get-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists_getAllByExternalAccountAndEventIds",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/associations/{marketingEventId}/lists": {
      "get": {
        "tags": [
          "List Associations"
        ],
        "summary": "Get lists associated with a marketing event",
        "description": "Gets lists associated with a marketing event by marketing event id",
        "operationId": "get-/marketing/v3/marketing-events/associations/{marketingEventId}/lists_getAllByMarketingEventId",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/email-create": {
      "post": {
        "tags": [
          "Add event attendees"
        ],
        "summary": "Record Participants by Email with Marketing Event Object Id",
        "description": "Records the participation of multiple HubSpot contacts in a Marketing Event using their email addresses.\n\nIf a contact does not exist, it will be automatically created. The contactProperties field is used exclusively for creating new contacts and will not update properties of existing contacts.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
        "operationId": "post-/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/email-create_recordByEmail",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/": {
      "get": {
        "tags": [
          "Basic"
        ],
        "summary": "Get all marketing event",
        "description": "Returns all Marketing Events available on the portal, along with their properties, regardless of whether they were created manually or through the application.\n\nThe marketing events returned by this endpoint are sorted by objectId.",
        "operationId": "get-/marketing/v3/marketing-events/_getAll",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/create": {
      "post": {
        "tags": [
          "Add event attendees"
        ],
        "summary": "Record Participants by ContactId with Marketing Event Object Id",
        "description": "Records the participation of multiple HubSpot contacts in a Marketing Event using their HubSpot contact IDs.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
        "operationId": "post-/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/create_recordByContactId",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/batch/update": {
      "post": {
        "tags": [
          "Batch"
        ],
        "summary": "Update Multiple Marketing Events by ObjectId",
        "description": "Updates multiple Marketing Events on the portal based on their objectId, if they exist.",
        "operationId": "post-/marketing/v3/marketing-events/batch/update_updateByObjectId",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 28,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/batch/archive": {
      "post": {
        "tags": [
          "Batch"
        ],
        "summary": "Delete Multiple Marketing Events by ObjectId",
        "description": "Deletes multiple Marketing Events from the portal based on their objectId, if they exist.\n\nResponses:\n204: Returned if all specified Marketing Events were successfully deleted.\n207: Returned if some objectIds did not correspond to any existing Marketing Events.",
        "operationId": "post-/marketing/v3/marketing-events/batch/archive_archiveByObjectId",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 1,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}": {
      "get": {
        "tags": [
          "Retrieve Participant State"
        ],
        "summary": "Read participations counters by Marketing Event external identifier",
        "description": "Read Marketing event's participations counters by externalAccountId and externalEventId pair.",
        "operationId": "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}_getParticipationsCountersByEventExternalId",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/{externalEventId}/identifiers": {
      "get": {
        "tags": [
          "Identifiers"
        ],
        "summary": "Find Marketing Events by External Event Id",
        "description": "This endpoint searches the portal for all Marketing Events whose externalEventId matches the value provided in the request.\n\nIt retrieves the objectId and additional event details for each matching Marketing Event.\n\nSince multiple Marketing Events can have the same externalEventId, the endpoint returns all matching results.\n\nNote: Marketing Events become searchable by externalEventId a few minutes after creation.",
        "operationId": "get-/marketing/v3/marketing-events/{externalEventId}/identifiers_searchPortalEvents",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/participations/{marketingEventId}": {
      "get": {
        "tags": [
          "Retrieve Participant State"
        ],
        "summary": "Read participations counters by Marketing Event internal identifier",
        "description": "Read Marketing event's participations counters by internal identifier marketingEventId.",
        "operationId": "get-/marketing/v3/marketing-events/participations/{marketingEventId}_getParticipationsCountersByMarketingEventId",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/events/delete": {
      "post": {
        "tags": [
          "Batch"
        ],
        "summary": "Delete Multiple Marketing Events by External Ids",
        "description": "Deletes multiple Marketing Events based on externalAccountId, externalEventId, and appId.\n\nOnly Marketing Events created by the same apps will be deleted; events from other apps cannot be removed by this endpoint. ",
        "operationId": "post-/marketing/v3/marketing-events/events/delete_archive",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 3,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/cancel": {
      "post": {
        "tags": [
          "Change property"
        ],
        "summary": "Mark a marketing event as cancelled",
        "description": "Mark a marketing event as cancelled.",
        "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_cancel",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}": {
      "put": {
        "tags": [
          "List Associations"
        ],
        "summary": "Associate a list with a marketing event",
        "description": "Associates a list with a marketing event by marketing event id and ILS list id",
        "operationId": "put-/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}_associateByMarketingEventId",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "List Associations"
        ],
        "summary": "Disassociate a list from a marketing event",
        "description": "Disassociates a list from a marketing event by marketing event id and ILS list id",
        "operationId": "delete-/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}_disassociateByMarketingEventId",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert": {
      "post": {
        "tags": [
          "Subscriber State Changes"
        ],
        "summary": "Record a subscriber state by contact email",
        "description": "Record a subscriber state between multiple HubSpot contacts and a marketing event, using contact email addresses. Note that the contact must already exist in HubSpot; a contact will not be created. The contactProperties field is used only when creating a new contact. These properties will not update existing contacts. ",
        "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_upsertByContactEmail",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}": {
      "put": {
        "tags": [
          "List Associations"
        ],
        "summary": "Associate a list with a marketing event",
        "description": "Associates a list with a marketing event by external account id, external event id, and ILS list id",
        "operationId": "put-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}_associateByExternalAccountAndEventIds",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "List Associations"
        ],
        "summary": "Disassociate a list from a marketing event",
        "description": "Disassociates a list from a marketing event by external account id, external event id, and ILS list id",
        "operationId": "delete-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}_disassociateByExternalAccountAndEventIds",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/complete": {
      "post": {
        "tags": [
          "Change property"
        ],
        "summary": "Mark a marketing event as completed",
        "description": "Mark a marketing event as completed",
        "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/events": {
      "post": {
        "tags": [
          "Basic"
        ],
        "summary": "Create a marketing event",
        "description": "Creates a new marketing event in HubSpot",
        "operationId": "post-/marketing/v3/marketing-events/events_create",
        "security": [
          {
            "oauth2": [
              "crm.objects.marketing_events.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "x-moar-primitive-count": 30,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown": {
      "get": {
        "tags": [
          "Retrieve Participant State"
        ],
        "summary": "Read participations breakdown by Contact identifier",
        "description": "Read Contact's participations by identifier - email or internal id.",
        "operationId": "get-/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown_getParticipationsBreakdownByContactId",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/{appId}/settings": {
      "get": {
        "tags": [
          "Settings"
        ],
        "summary": "Retrieve the application settings",
        "description": "Retrieve the current settings for the application.",
        "operationId": "get-/marketing/v3/marketing-events/{appId}/settings_getAll",
        "security": [
          {
            "developer_hapikey": []
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "post": {
        "tags": [
          "Settings"
        ],
        "summary": "Update the application settings",
        "description": "Create or update the current settings for the application.",
        "operationId": "post-/marketing/v3/marketing-events/{appId}/settings_update",
        "security": [
          {
            "developer_hapikey": []
          }
        ],
        "x-moar-primitive-count": 1,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/marketing-events/events/search": {
      "get": {
        "tags": [
          "Identifiers"
        ],
        "summary": "Find App-Specific Marketing Events by External Event Id",
        "description": "Retrieves Marketing Events where the externalEventId matches the value provided in the request, limited to events created by the app making the request.\n\nMarketing Events created by other apps will not be included in the results.",
        "operationId": "get-/marketing/v3/marketing-events/events/search_doSearch",
        "security": [
          {
            "private_apps": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.marketing_events.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v4/email/single-send": {
      "post": {
        "tags": [
          "Single_Send"
        ],
        "summary": "Send an email",
        "description": "Send a template email to a specific recipient.",
        "operationId": "post-/marketing/v4/email/single-send",
        "security": [
          {
            "oauth2": [
              "marketing-email"
            ]
          },
          {
            "private_apps": [
              "marketing-email"
            ]
          },
          {
            "oauth2": [
              "transactional-email"
            ]
          },
          {
            "private_apps": [
              "transactional-email"
            ]
          }
        ],
        "x-hubspot-rate-limit-exemptions": [
          "daily",
          "ten-secondly"
        ],
        "x-moar-primitive-count": 7,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/transactional/single-email/send": {
      "post": {
        "tags": [
          "Single send"
        ],
        "summary": "Send a single transactional email asynchronously.",
        "description": "Asynchronously send a transactional email. Returns the status of the email send with a statusId that can be used to continuously query for the status using the Email Send Status API.",
        "operationId": "post-/marketing/v3/transactional/single-email/send_sendEmail",
        "security": [
          {
            "oauth2": [
              "transactional-email"
            ]
          },
          {
            "private_apps": [
              "transactional-email"
            ]
          }
        ],
        "x-hubspot-rate-limit-exemptions": [
          "daily",
          "ten-secondly"
        ],
        "x-moar-primitive-count": 7,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/transactional/smtp-tokens": {
      "get": {
        "tags": [
          "Public SMTP tokens"
        ],
        "summary": "Query SMTP API tokens by campaign name or an emailCampaignId.",
        "description": "Query multiple SMTP API tokens by campaign name or a single token by emailCampaignId.",
        "operationId": "get-/marketing/v3/transactional/smtp-tokens_getTokensPage",
        "security": [
          {
            "oauth2": [
              "transactional-email"
            ]
          },
          {
            "private_apps": [
              "transactional-email"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "post": {
        "tags": [
          "Public SMTP tokens"
        ],
        "summary": "Create a SMTP API token.",
        "description": "Create a SMTP API token.",
        "operationId": "post-/marketing/v3/transactional/smtp-tokens_createToken",
        "security": [
          {
            "oauth2": [
              "transactional-email"
            ]
          },
          {
            "private_apps": [
              "transactional-email"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/transactional/smtp-tokens/{tokenId}/password-reset": {
      "post": {
        "tags": [
          "Public SMTP tokens"
        ],
        "summary": "Reset the password of an existing token.",
        "description": "Allows the creation of a replacement password for a given token. Once the password is successfully reset, the old password for the token will be invalid.",
        "operationId": "post-/marketing/v3/transactional/smtp-tokens/{tokenId}/password-reset_resetPassword",
        "security": [
          {
            "oauth2": [
              "transactional-email"
            ]
          },
          {
            "private_apps": [
              "transactional-email"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/marketing/v3/transactional/smtp-tokens/{tokenId}": {
      "get": {
        "tags": [
          "Public SMTP tokens"
        ],
        "summary": "Query a single token by ID.",
        "description": "Query a single token by ID.",
        "operationId": "get-/marketing/v3/transactional/smtp-tokens/{tokenId}_getTokenById",
        "security": [
          {
            "oauth2": [
              "transactional-email"
            ]
          },
          {
            "private_apps": [
              "transactional-email"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Public SMTP tokens"
        ],
        "summary": "Delete a single token by ID.",
        "description": "Delete a single token by ID.",
        "operationId": "delete-/marketing/v3/transactional/smtp-tokens/{tokenId}_archiveToken",
        "security": [
          {
            "oauth2": [
              "transactional-email"
            ]
          },
          {
            "private_apps": [
              "transactional-email"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
            "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
            "scopes": {
              "marketing.campaigns.read": "Read marketing campaigns",
              "marketing.campaigns.write": "Write marketing campaigns",
              "marketing.campaigns.revenue.read": "Read campaigns attribution revenue",
              "forms": "Read from and write to my Forms",
              "content": "Read from and write to my Content",
              "marketing-email": "Marketing Single Send API access",
              "transactional-email": "Transactional Emails",
              "crm.objects.marketing_events.read": "Read marketing events",
              "crm.objects.marketing_events.write": "Write marketing events"
            }
          }
        }
      },
      "private_apps": {
        "type": "apiKey",
        "name": "private-app",
        "in": "header"
      },
      "developer_hapikey": {
        "type": "apiKey",
        "name": "hapikey",
        "in": "query"
      }
    }
  },
  "x-hubspot-product-tier-requirements": {
    "marketing": "PROFESSIONAL",
    "sales": "FREE",
    "service": "FREE",
    "cms": "FREE",
    "commerce": "FREE",
    "crmHub": "FREE",
    "dataHub": "FREE"
  }
}
